### PR TITLE
Fixes #285: Added preview for markdown editors

### LINKED ISSUE #285: wiki preview does not work

### PR DESCRIPTION
**Pull request by samdark**
markdown_editor_preview

#285

### CODE REVIEW

File: controllers/SiteController.php [hunk 1]
```diff
@@ -241,4 +240,10 @@ public function actionCommunity()
         $this->sectionTitle = 'Community Resources';
         return $this->render('community');
     }
+
+    public function actionRenderMarkdown()
+    {
+        $markdown = Yii::$app->request->post('content');
+        return Yii::$app->formatter->asGuideMarkdown($markdown);
```
Comment (cebe) [inline controllers/SiteController.php]: we should probably restrict this to logged in users or rate limit it, otherwise one could send arbitrary content for markdown parsing here.

**Comment by cebe** [comment]
this also waits for #300

File: controllers/SiteController.php (hunk 1 above)
Comment (samdark) [reply controllers/SiteController.php]: Done.
